### ISSUE TITLE
Registry path to vb6.exe incorrect for x64

### ISSUE THREAD

**Issue by Bryce-L** [nant/nantcontrib#34]
See the third comment under the http://stackoverflow.com/a/19402156/154637 answer for more details.

In Vb6Task.cs, nantcontrib is looking for vb6.exe under: SOFTWARE\Microsoft\VisualStudio\6.0\Setup\Microsoft Visual Basic

On x64 platforms, it is located under: SOFTWARE\Wow6432Node\Microsoft\VisualStudio\6.0\Setup\Microsoft Visual Basic

**Comment by rmboggs** [comment]
Merged.  Thanks for the contribution.
